/**
 * Export the list of imported fonts defined in main.css
 */
export const SEGUE_FONTS = [
  { value: "Almendra", label: "Almendra" },
  { value: "Balthazar", label: "Balthazar" },
  { value: "Bellefair", label: "Bellefair" },
  { value: "Chau Philomene One", label: "Chau Philomene One" },
  { value: "Codystar", label: "Codystar" },
  { value: "Creepster", label: "Creepster" },
  { value: "Ewert", label: "Ewert" },
  { value: "Frijole", label: "Frijole" },
  { value: "Germania One", label: "Germania One" },
  { value: "Goudy Bookletter 1911", label: "Goudy Bookletter 1911" },
  { value: "Great Vibes", label: "Great Vibes" },
  { value: "Grenze Gotisch", label: "Grenze Gotisch" },
  { value: "Griffy", label: "Griffy" },
  { value: "IM Fell English", label: "IM Fell English" },
  { value: "Love Ya Like A Sister", label: "Love Ya Like A Sister" },
  { value: "Macondo", label: "Macondo" },
  { value: "Metal Mania", label: "Metal Mania" },
  { value: "Modern Antiqua", label: "Modern Antiqua" },
  { value: "Nosifer", label: "Nosifer" },
  { value: "Permanent Marker", label: "Permanent Marker" },
  { value: "Pirata One", label: "Pirata One" },
  { value: "Quintessential", label: "Quintessential" },
  { value: "Rock Salt", label: "Rock Salt" },
  { value: "Rubik Distressed", label: "Rubik Distressed" },
  { value: "Sancreek", label: "Sancreek" },
  { value: "Sixtyfour Convergence", label: "Sixtyfour Convergence" },
  { value: "Sixtyfour", label: "Sixtyfour" },
  { value: "Special Elite", label: "Special Elite" },
  { value: "Syne Mono", label: "Syne Mono" },
  { value: "Trade Winds", label: "Trade Winds" },
  { value: "UnifrakturMaguntia", label: "UnifrakturMaguntia" },
  { value: "VT323", label: "VT323" },
];
